feat(bake): allow pull of single saved bake target
depot/pull-action pull request #4
Opened 2024-03-03 14:45 UTC by goller

2024-03-03 21:53 UTC, jacobwgillespie commented on action.yml
> +    required: false
I believe we do need an explicit default value if `required: false`:

```suggestion
    default: ''
    required: false
```

2024-03-04 15:03 UTC, kylegalbraith requested changes

2024-03-04 15:03 UTC, kylegalbraith commented on src/context.ts
> +    token: core.getInput('target'),
This is referencing the wrong input.

2024-03-04 16:14 UTC, jacobwgillespie approved these changes
🚀

2024-03-04 16:21 UTC, merged